In [3]:
!pip install pandas ipywidgets textblob scikit-learn tqdm numpy openpyxl matplotlib sentence-transformers cupy xgboost seaborn flask streamlit joblib textblob google-generativeai python-dotenv emoji

Requirement already satisfied: pandas in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (2.3.0)
Requirement already satisfied: ipywidgets in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (8.1.7)
Requirement already satisfied: textblob in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (0.19.0)
Requirement already satisfied: scikit-learn in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (1.7.0)
Requirement already satisfied: tqdm in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (4.67.1)
Requirement already satisfied: numpy in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (2.3.1)
Requirement already satisfied: openpyxl in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (3.1.5)
Requirement already satisfied: matplotlib in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (3.10.3)
Requirement already satisfied: sentence-transformers in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (5.0.0)
Collecting cupy
  Using cached cupy-13.5.1.tar.gz (3.5 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: xgboost in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (3.0.2)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: flask in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (3.1.1)
Requirement already satisfied: streamlit in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (1.46.1)
Requirement already satisfied: joblib in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (1.5.1)
Collecting google-generativeai
  Using cached google_generativeai-0.8.5-py3-none-any.whl.metadata (3.9 kB)
Collecting python-dotenv
  Downloading python_dotenv-1.1.1-py3-none-any.whl.metadata (24 kB)
Collecting emoji
  Using cached emoji-2.14.1-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: comm>=0.1.3 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from ipywidgets) (0.2.2)
Requirement already satisfied: ipython>=6.1.0 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from ipywidgets) (9.3.0)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from ipywidgets) (4.0.14)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from ipywidgets) (3.0.15)
Requirement already satisfied: nltk>=3.9 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from textblob) (3.9.1)
Requirement already satisfied: scipy>=1.8.0 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from scikit-learn) (1.16.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: colorama in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from tqdm) (0.4.6)
Requirement already satisfied: et-xmlfile in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from matplotlib) (4.58.4)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from sentence-transformers) (4.53.1)
Requirement already satisfied: torch>=1.11.0 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from sentence-transformers) (2.7.1+cu118)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from sentence-transformers) (0.33.2)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from sentence-transformers) (4.14.0)
Requirement already satisfied: filelock in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (3.18.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.11.6)
Requirement already satisfied: requests in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.32.4)
Requirement already satisfied: tokenizers<0.22,>=0.21 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.5.3)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.5.1)
Collecting fastrlock>=0.5 (from cupy)
  Using cached fastrlock-0.8.3-cp311-cp311-win_amd64.whl.metadata (7.9 kB)
Requirement already satisfied: blinker>=1.9.0 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from flask) (1.9.0)
Requirement already satisfied: click>=8.1.3 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from flask) (8.2.1)
Requirement already satisfied: itsdangerous>=2.2.0 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from flask) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from flask) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from flask) (3.0.2)
Requirement already satisfied: werkzeug>=3.1.0 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from flask) (3.1.3)
Requirement already satisfied: altair<6,>=4.0 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: cachetools<7,>=4.0 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from streamlit) (6.1.0)
Requirement already satisfied: protobuf<7,>=3.20 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from streamlit) (6.31.1)
Requirement already satisfied: pyarrow>=7.0 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from streamlit) (20.0.0)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from streamlit) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from streamlit) (3.1.44)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from streamlit) (0.9.1)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: jsonschema>=3.0 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from altair<6,>=4.0->streamlit) (4.24.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from altair<6,>=4.0->streamlit) (1.45.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (2025.6.15)
Collecting google-ai-generativelanguage==0.6.15 (from google-generativeai)
  Using cached google_ai_generativelanguage-0.6.15-py3-none-any.whl.metadata (5.7 kB)
Collecting google-api-core (from google-generativeai)
  Using cached google_api_core-2.25.1-py3-none-any.whl.metadata (3.0 kB)
Collecting google-api-python-client (from google-generativeai)
  Using cached google_api_python_client-2.177.0-py3-none-any.whl.metadata (7.0 kB)
Collecting google-auth>=2.15.0 (from google-generativeai)
  Using cached google_auth-2.40.3-py2.py3-none-any.whl.metadata (6.2 kB)
Collecting pydantic (from google-generativeai)
  Downloading pydantic-2.11.7-py3-none-any.whl.metadata (67 kB)
Collecting proto-plus<2.0.0dev,>=1.22.3 (from google-ai-generativelanguage==0.6.15->google-generativeai)
  Using cached proto_plus-1.26.1-py3-none-any.whl.metadata (2.2 kB)
Collecting protobuf<7,>=3.20 (from streamlit)
  Using cached protobuf-5.29.5-cp310-abi3-win_amd64.whl.metadata (592 bytes)
Collecting googleapis-common-protos<2.0.0,>=1.56.2 (from google-api-core->google-generativeai)
  Using cached googleapis_common_protos-1.70.0-py3-none-any.whl.metadata (9.3 kB)
Collecting grpcio<2.0.0,>=1.33.2 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai)
  Using cached grpcio-1.74.0-cp311-cp311-win_amd64.whl.metadata (4.0 kB)
Collecting grpcio-status<2.0.0,>=1.33.2 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai)
  Using cached grpcio_status-1.74.0-py3-none-any.whl.metadata (1.1 kB)
Collecting cachetools<7,>=4.0 (from streamlit)
  Using cached cachetools-5.5.2-py3-none-any.whl.metadata (5.4 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth>=2.15.0->google-generativeai)
  Using cached pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting rsa<5,>=3.1.4 (from google-auth>=2.15.0->google-generativeai)
  Using cached rsa-4.9.1-py3-none-any.whl.metadata (5.6 kB)
INFO: pip is looking at multiple versions of grpcio-status to determine which version is compatible with other requirements. This could take a while.
Collecting grpcio-status<2.0.0,>=1.33.2 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai)
  Using cached grpcio_status-1.73.1-py3-none-any.whl.metadata (1.1 kB)
  Using cached grpcio_status-1.73.0-py3-none-any.whl.metadata (1.1 kB)
  Using cached grpcio_status-1.72.2-py3-none-any.whl.metadata (1.1 kB)
  Using cached grpcio_status-1.72.1-py3-none-any.whl.metadata (1.1 kB)
  Using cached grpcio_status-1.71.2-py3-none-any.whl.metadata (1.1 kB)
Collecting pyasn1>=0.1.3 (from rsa<5,>=3.1.4->google-auth>=2.15.0->google-generativeai)
  Using cached pyasn1-0.6.1-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: decorator in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.1.7)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.51)
Requirement already satisfied: pygments>=2.4.0 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (2.19.2)
Requirement already satisfied: stack_data in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.4)
Requirement already satisfied: attrs>=22.2.0 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.26.0)
Requirement already satisfied: six>=1.5 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\swaya\onedrive\documents\github\ai_and_dev_swayam_pandey_csot\.venv\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Collecting httplib2<1.0.0,>=0.19.0 (from google-api-python-client->google-generativeai)
  Using cached httplib2-0.22.0-py3-none-any.whl.metadata (2.6 kB)
Collecting google-auth-httplib2<1.0.0,>=0.2.0 (from google-api-python-client->google-generativeai)
  Using cached google_auth_httplib2-0.2.0-py2.py3-none-any.whl.metadata (2.2 kB)
Collecting uritemplate<5,>=3.0.1 (from google-api-python-client->google-generativeai)
  Using cached uritemplate-4.2.0-py3-none-any.whl.metadata (2.6 kB)
Collecting annotated-types>=0.6.0 (from pydantic->google-generativeai)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.33.2 (from pydantic->google-generativeai)

  error: subprocess-exited-with-error

  × Building wheel for cupy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [78 lines of output]
      Clearing directory: C:\Users\swaya\AppData\Local\Temp\pip-install-cstpdo1g\cupy_2d47ecb2b12840faa345c2909b2af2a9\cupy\.data
      Generating CUPY_CACHE_KEY from header files...
      CUPY_CACHE_KEY (1729 files matching C:\Users\swaya\AppData\Local\Temp\pip-install-cstpdo1g\cupy_2d47ecb2b12840faa345c2909b2af2a9\cupy\_core\include\**): 62426478e3e7017e0abfdd71b0667fdffa294302
      **************************************************
      *** WARNING: nvcc path != CUDA_PATH
      *** WARNING: nvcc path: None
      *** WARNING: CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9
      **************************************************
      Looking for NVTX: C:\Program Files\NVIDIA Corporation\Nsight Systems *\target-windows-x64\nvtx
      Using NVTX at: C:\Program Files\NVIDIA Corporation\Nsight Systems 2025.1.3\target-windows-x64\nvtx

      -------- Configuring Module: cuda --------
      Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      **************************************************
      *** WARNING: Cannot check compute capability
      Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      **************************************************

      ************************************************************
      * CuPy Configuration Summary                               *
      ************************************************************

      Build Environment:
        Include directories: ['C:\\Users\\swaya\\AppData\\Local\\Temp\\pip-install-cstpdo1g\\cupy_2d47ecb2b12840faa345c2909b2af2a9\\cupy/_core/include\\cupy/_cccl/libcudacxx', 'C:\\Users\\swaya\\AppData\\Local\\Temp\\pip-install-cstpdo1g\\cupy_2d47ecb2b12840faa345c2909b2af2a9\\cupy/_core/include\\cupy/_cccl/thrust', 'C:\\Users\\swaya\\AppData\\Local\\Temp\\pip-install-cstpdo1g\\cupy_2d47ecb2b12840faa345c2909b2af2a9\\cupy/_core/include\\cupy/_cccl/cub', 'C:\\Users\\swaya\\AppData\\Local\\Temp\\pip-install-cstpdo1g\\cupy_2d47ecb2b12840faa345c2909b2af2a9\\cupy/_core/include', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.9\\include', 'C:\\Program Files\\NVIDIA Corporation\\Nsight Systems 2025.1.3\\target-windows-x64\\nvtx\\include']
        Library directories: ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.9\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.9\\lib\\x64']
        nvcc command       : ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.9\\bin/nvcc.exe']
        hipcc command      : (not found)

      Environment Variables:
        CFLAGS          : (none)
        LDFLAGS         : (none)
        LIBRARY_PATH    : (none)
        CUDA_PATH       : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9
        NVCC            : (none)
        HIPCC           : (none)
        ROCM_HOME       : (none)

      Modules:
        cuda      : No
          -> Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'cufft.h', 'curand.h', 'cusparse.h']
          -> Check your CFLAGS environment variable.

      ERROR: CUDA could not be found on your system.

      HINT: You are trying to build CuPy from source, which is NOT recommended for general use.
            Please consider using binary packages instead.

      Please refer to the Installation Guide for details:
      https://docs.cupy.dev/en/stable/install.html

      ************************************************************

      Traceback (most recent call last):
        File "c:\Users\swaya\OneDrive\Documents\GitHub\AI_and_Dev_Swayam_Pandey_CSoT\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 389, in <module>
          main()
        File "c:\Users\swaya\OneDrive\Documents\GitHub\AI_and_Dev_Swayam_Pandey_CSoT\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "c:\Users\swaya\OneDrive\Documents\GitHub\AI_and_Dev_Swayam_Pandey_CSoT\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 280, in build_wheel
          return _build_backend().build_wheel(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\swaya\AppData\Local\Temp\pip-build-env-h6ts4pdj\overlay\Lib\site-packages\setuptools\build_meta.py", line 435, in build_wheel
          return _build(['bdist_wheel', '--dist-info-dir', str(metadata_directory)])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\swaya\AppData\Local\Temp\pip-build-env-h6ts4pdj\overlay\Lib\site-packages\setuptools\build_meta.py", line 423, in _build
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\swaya\AppData\Local\Temp\pip-build-env-h6ts4pdj\overlay\Lib\site-packages\setuptools\build_meta.py", line 404, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\swaya\AppData\Local\Temp\pip-build-env-h6ts4pdj\overlay\Lib\site-packages\setuptools\build_meta.py", line 317, in run_setup
          exec(code, locals())
        File "<string>", line 59, in <module>
        File "C:\Users\swaya\AppData\Local\Temp\pip-install-cstpdo1g\cupy_2d47ecb2b12840faa345c2909b2af2a9\install\cupy_builder\cupy_setup_build.py", line 562, in get_ext_modules
          extensions = make_extensions(ctx, compiler, use_cython)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\swaya\AppData\Local\Temp\pip-install-cstpdo1g\cupy_2d47ecb2b12840faa345c2909b2af2a9\install\cupy_builder\cupy_setup_build.py", line 403, in make_extensions
          raise Exception('Your CUDA environment is invalid. '
      Exception: Your CUDA environment is invalid. Please check above error log.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cupy
ERROR: Failed to build installable wheels for some pyproject.toml based projects (cupy)

In [1]:
import pandas as pd

df = pd.read_excel("behaviour_simulation_train.xlsx", parse_dates = ['date']) #add path to the dataset

# Data cleaning
df['content'] = df['content'].astype(str).str.strip()
df['username'] = df['username'].astype(str).str.strip()
df['media'] = df['media'].astype(str).str.strip()

# Feature engineering
df['hour'] = df['date'].dt.hour
df['day_of_week'] = df['date'].dt.day_name()
df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year

media_dict = {'P':'Photo', 'V':'Video', 'G':'Gif'}
df['media_type'] = df['media'].str[1].map(media_dict)

df['word_count'] = df['content'].str.split().str.len()
df['char_count'] = df['content'].str.len()

In [5]:
!pip install emoji

Collecting emoji
  Using cached emoji-2.14.1-py3-none-any.whl.metadata (5.7 kB)
Using cached emoji-2.14.1-py3-none-any.whl (590 kB)
Installing collected packages: emoji
Successfully installed emoji-2.14.1

In [5]:
import emoji

def count_emojis(text):
    return sum(1 for char in text if char in emoji.EMOJI_DATA)

df['emoji_count'] = df['content'].apply(lambda x: count_emojis(x))
df['hashtag_count'] = df['content'].str.count(r'#\w+')

In [6]:
# Sentiment analysis using TextBlob, adding polarity and subjectivity as features

from textblob import TextBlob
from tqdm.notebook import tqdm

def analyze_sentiments(texts):
    polarities = []
    subjectivities = []
    
    # Use tqdm for progress tracking
    for text in tqdm(texts, desc="Analyzing texts"):
        analysis = TextBlob(text)
        polarities.append(analysis.sentiment.polarity)
        subjectivities.append(analysis.sentiment.subjectivity)
    
    return polarities, subjectivities

df['sentiment_polarity'], df['sentiment_subjectivity'] = analyze_sentiments(df['content'])

Analyzing texts:   0%|          | 0/300000 [00:00<?, ?it/s]

In [7]:
# rmse when predicting average likes for each row
# rmse: 4931.455200077609
from sklearn.metrics import mean_squared_error

import numpy as np

average = df['likes'].mean()

rmse = np.sqrt(mean_squared_error(df['likes'], average * np.ones_like(df['likes'])))
print("RMSE:", rmse)

RMSE: 4931.455200077609

In [8]:
usernames_data = pd.read_csv("usernames_data_x.csv", parse_dates=['createdAt'])
usernames_data.info()
display(usernames_data.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2249 entries, 0 to 2248
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   userName         2249 non-null   object
 1   id               2249 non-null   float64
 2   name             2249 non-null   object
 3   followers        2249 non-null   int64
 4   following        2249 non-null   int64
 5   isBlueVerified   2249 non-null   bool
 6   verifiedType     604 non-null    object
 7   statusesCount    2249 non-null   int64
 8   mediaCount       2249 non-null   int64
 9   favouritesCount  2249 non-null   int64
 10  createdAt        2249 non-null   datetime64[ns, UTC]
 11  location         1788 non-null   object
 12  description      2184 non-null   object
 13  canDm            2249 non-null   bool
dtypes: bool(2), datetime64[ns, UTC](1), float64(1), int64(5), object(5)
memory usage: 215.4+ KB

userName              0
id                    0
name                  0
followers             0
following             0
isBlueVerified        0
verifiedType       1645
statusesCount         0
mediaCount            0
favouritesCount       0
createdAt             0
location            461
description          65
canDm                 0
dtype: int64

In [9]:
if df.shape[1]<30: # so that duplicate we do not merge again by mistake and duplicate columns are made
    # (after merging number of columns will be 30)
    df = pd.merge(df, usernames_data, left_on='username', right_on='userName', how='left')
print(df.info())
display(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 32 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id_x                    300000 non-null  int64
 1   date                    300000 non-null  datetime64[ns]
 2   likes                   300000 non-null  int64
 3   content                 300000 non-null  object
 4   username                300000 non-null  object
 5   media                   300000 non-null  object
 6   inferred company        300000 non-null  object
 7   hour                    300000 non-null  int32
 8   day_of_week             300000 non-null  object
 9   month                   300000 non-null  int32
 10  year                    300000 non-null  int32
 11  media_type              300000 non-null  object
 12  word_count              300000 non-null  int64
 13  char_count              300000 non-null  int64
 14  emoji_count             300000 non-null  int64
 15  hashtag_count           300000 non-null  int64
 16  sentiment_polarity      300000 non-null  float64
 17  sentiment_subjectivity  300000 non-null  float64
 18  userName                288344 non-null  object
 19  id_y                    288344 non-null  float64
 20  name                    288344 non-null  object
 21  followers               288344 non-null  float64
 22  following               288344 non-null  float64
 23  isBlueVerified          288344 non-null  object
 24  verifiedType            121436 non-null  object
 25  statusesCount           288344 non-null  float64
 26  mediaCount              288344 non-null  float64
 27  favouritesCount         288344 non-null  float64
 28  createdAt               288344 non-null  datetime64[ns, UTC]
 29  location                231415 non-null  object
 30  description             284716 non-null  object
 31  canDm                   288344 non-null  object
dtypes: datetime64[ns, UTC](1), datetime64[ns](1), float64(8), int32(3), int64(6), object(13)
memory usage: 69.8+ MB
None

id_x                           0
date                           0
likes                          0
content                        0
username                       0
media                          0
inferred company               0
hour                           0
day_of_week                    0
month                          0
year                           0
media_type                     0
word_count                     0
char_count                     0
emoji_count                    0
hashtag_count                  0
sentiment_polarity             0
sentiment_subjectivity         0
userName                   11656
id_y                       11656
name                       11656
followers                  11656
following                  11656
isBlueVerified             11656
verifiedType              178564
statusesCount              11656
mediaCount                 11656
favouritesCount            11656
createdAt                  11656
location                   68585
description                15284
canDm                      11656
dtype: int64

In [10]:
df['username_avg_likes'] = df.groupby('username')['likes'].transform('mean')
df['company_avg_likes'] = df.groupby('inferred company')['likes'].transform('mean')

In [30]:
df.info()
display(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 34 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id_x                    300000 non-null  int64
 1   date                    300000 non-null  datetime64[ns]
 2   likes                   300000 non-null  int64
 3   content                 300000 non-null  object
 4   username                300000 non-null  object
 5   media                   300000 non-null  object
 6   inferred company        300000 non-null  object
 7   hour                    300000 non-null  int32
 8   day_of_week             300000 non-null  object
 9   month                   300000 non-null  int32
 10  year                    300000 non-null  int32
 11  media_type              300000 non-null  object
 12  word_count              300000 non-null  int64
 13  char_count              300000 non-null  int64
 14  sentiment_polarity      300000 non-null  float64
 15  sentiment_subjectivity  300000 non-null  float64
 16  userName                288344 non-null  object
 17  id_y                    288344 non-null  float64
 18  name                    288344 non-null  object
 19  followers               288344 non-null  float64
 20  following               288344 non-null  float64
 21  isBlueVerified          288344 non-null  object
 22  verifiedType            121436 non-null  object
 23  statusesCount           288344 non-null  float64
 24  mediaCount              288344 non-null  float64
 25  favouritesCount         288344 non-null  float64
 26  createdAt               288344 non-null  datetime64[ns, UTC]
 27  location                231415 non-null  object
 28  description             284716 non-null  object
 29  canDm                   288344 non-null  object
 30  username_avg_likes      300000 non-null  float64
 31  company_avg_likes       300000 non-null  float64
 32  emoji_count             300000 non-null  int64
 33  hashtag_count           300000 non-null  int64
dtypes: datetime64[ns, UTC](1), datetime64[ns](1), float64(10), int32(3), int64(6), object(13)
memory usage: 74.4+ MB

id_x                           0
date                           0
likes                          0
content                        0
username                       0
media                          0
inferred company               0
hour                           0
day_of_week                    0
month                          0
year                           0
media_type                     0
word_count                     0
char_count                     0
sentiment_polarity             0
sentiment_subjectivity         0
userName                   11656
id_y                       11656
name                       11656
followers                  11656
following                  11656
isBlueVerified             11656
verifiedType              178564
statusesCount              11656
mediaCount                 11656
favouritesCount            11656
createdAt                  11656
location                   68585
description                15284
canDm                      11656
username_avg_likes             0
company_avg_likes              0
emoji_count                    0
hashtag_count                  0
dtype: int64

In [11]:
display(df.head())

,id_x,date,likes,content,username,media,inferred company,hour,day_of_week,month,...,verifiedType,statusesCount,mediaCount,favouritesCount,createdAt,location,description,canDm,username_avg_likes,company_avg_likes
0,1,2020-12-12 00:47:00,1,"Spend your weekend morning with a Ham, Egg, an...",TimHortonsPH,[Photo(previewUrl='https://pbs.twimg.com/media...,tim hortons,0,Saturday,12,...,NaN,931.0,687.0,954.0,2016-11-04 05:57:45+00:00,Republic of the Philippines,Welcome to the official account of Tim Hortons...,False,3.670270,160.179678
1,2,2018-06-30 10:04:20,2750,Watch rapper <mention> freestyle for over an H...,IndyMusic,[Photo(previewUrl='https://pbs.twimg.com/media...,independent,10,Saturday,6,...,NaN,31733.0,4853.0,104.0,2008-11-11 12:43:57+00:00,London,"Music news, reviews, and feature stories from ...",False,441.894737,49.258918
2,3,2020-09-29 19:47:28,57,Canadian Armenian community demands ban on mil...,CBCCanada,[Photo(previewUrl='https://pbs.twimg.com/media...,cbc,19,Tuesday,9,...,NaN,93717.0,53557.0,11.0,2009-01-14 03:42:38+00:00,Canada,"Canadian news and features, and the Politics B...",False,95.671698,204.387701
3,4,2020-10-01 11:40:09,152,"1st in Europe to be devastated by COVID-19, It...",MKWilliamsRome,[Photo(previewUrl='https://pbs.twimg.com/media...,williams,11,Thursday,10,...,NaN,5739.0,1294.0,10180.0,2012-08-13 10:53:48+00:00,NaN,"Report on radio & TV & write on Italy, Europe ...",False,256.151515,2093.835052
4,5,2018-10-19 14:30:46,41,Congratulations to Pauletha Butts of <mention>...,BGISD,[Photo(previewUrl='https://pbs.twimg.com/media...,independent,14,Friday,10,...,NaN,7397.0,2347.0,5311.0,2009-02-26 21:06:29+00:00,"Bowling Green, Kentucky","Every day, accomplishments of students and emp...",False,63.403226,49.258918

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import seaborn as sns

# computing the correlation matrix
corr_matrix = df[['likes', 
    'followers', 
    'following', 
    'statusesCount',
    'mediaCount', 
    'favouritesCount', 
    'sentiment_polarity', 
    'sentiment_subjectivity',
    'char_count',
    'word_count',
    'username_avg_likes',
    'company_avg_likes',
    'emoji_count',
    'hashtag_count']].corr()

display(corr_matrix)

# plotting heatmap
# plt.figure(figsize=(8, 6))
# sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', center=0, fmt=".2f")
# plt.title('Correlation Matrix Heatmap')
# plt.tight_layout()
# plt.show()

,likes,followers,following,statusesCount,mediaCount,favouritesCount,sentiment_polarity,sentiment_subjectivity,char_count,word_count,username_avg_likes,company_avg_likes,emoji_count,hashtag_count
likes,1.000000,0.114841,-0.004574,-0.020911,-0.005188,0.030032,0.002094,0.007150,-0.015755,-0.003997,0.447372,0.367532,0.036158,-0.002787
followers,0.114841,1.000000,-0.038959,0.184327,0.374044,-0.085150,-0.066777,0.000332,0.102609,0.112605,0.256715,0.287338,-0.073130,-0.166777
following,-0.004574,-0.038959,1.000000,0.065142,-0.100997,0.112062,0.023166,0.029696,0.035301,0.036914,-0.010226,-0.007884,0.054217,0.040726
statusesCount,-0.020911,0.184327,0.065142,1.000000,0.730172,-0.099159,-0.132805,-0.125445,-0.191989,-0.193390,-0.046745,-0.049138,-0.105030,-0.235161
mediaCount,-0.005188,0.374044,-0.100997,0.730172,1.000000,-0.174254,-0.191893,-0.182301,-0.233076,-0.242162,-0.011596,-0.013236,-0.150466,-0.314259
favouritesCount,0.030032,-0.085150,0.112062,-0.099159,-0.174254,1.000000,0.017523,0.021523,-0.065749,-0.032158,0.067134,0.116662,0.063183,-0.064780
sentiment_polarity,0.002094,-0.066777,0.023166,-0.132805,-0.191893,0.017523,1.000000,0.468945,0.134472,0.138816,-0.007275,0.003001,0.059095,0.113603
sentiment_subjectivity,0.007150,0.000332,0.029696,-0.125445,-0.182301,0.021523,0.468945,1.000000,0.261735,0.273016,0.010336,0.009129,0.034796,0.086073
char_count,-0.015755,0.102609,0.035301,-0.191989,-0.233076,-0.065749,0.134472,0.261735,1.000000,0.971636,-0.038806,-0.045682,0.010951,0.305030
word_count,-0.003997,0.112605,0.036914,-0.193390,-0.242162,-0.032158,0.138816,0.273016,0.971636,1.000000,-0.014384,-0.021134,0.036770,0.221868
username_avg_likes,0.447372,0.256715,-0.010226,-0.046745,-0.011596,0.067134,-0.007275,0.010336,-0.038806,-0.014384,1.000000,0.819443,0.075334,-0.028186
company_avg_likes,0.367532,0.287338,-0.007884,-0.049138,-0.013236,0.116662,0.003001,0.009129,-0.045682,-0.021134,0.819443,1.000000,0.092036,-0.026309
emoji_count,0.036158,-0.073130,0.054217,-0.105030,-0.150466,0.063183,0.059095,0.034796,0.010951,0.036770,0.075334,0.092036,1.000000,0.057597
hashtag_count,-0.002787,-0.166777,0.040726,-0.235161,-0.314259,-0.064780,0.113603,0.086073,0.305030,0.221868,-0.028186,-0.026309,0.057597,1.000000

In [14]:
def get_features(X_train, X_test, numerial_features=[], categorical_features=[], avg_likes=[], bert_embeddings=None):
    X_train_final = np.hstack([
        X_train[i].values.reshape(-1, 1) for i in numerial_features
    ])
    X_test_final = np.hstack([
        X_test[i].values.reshape(-1, 1) for i in numerial_features
    ])

    from sklearn.preprocessing import OneHotEncoder
    
    encoders = {}  # To store encoders for each categorical feature
    for i in categorical_features:
        encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
        encoder.fit(X_train[[i]])
        encoded_train = encoder.transform(X_train[[i]])
        encoded_test = encoder.transform(X_test[[i]])
        X_train_final = np.hstack([X_train_final, encoded_train])
        X_test_final = np.hstack([X_test_final, encoded_test])
        encoders[i] = encoder  # Store the encoder for later use
        import sys
    
    for i in avg_likes:
        avg_likes_train = X_train.groupby(i)['likes'].mean().reindex(X_train[i])
        avg_likes_test = X_test.groupby(i)['likes'].mean().reindex(X_test[i])
        X_train_final = np.hstack([X_train_final, avg_likes_train.values.reshape(-1, 1)])
        X_test_final = np.hstack([X_test_final, avg_likes_test.values.reshape(-1, 1)])
    print('features obtained')
    return X_train_final, X_test_final, encoders

In [15]:
def random_forest_regressor(X_train_final, y_train, X_test_final, y_test, n_estimators=100):
    from sklearn.ensemble import RandomForestRegressor
    from sklearn.metrics import mean_squared_error
    import numpy as np
    
    rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
    rf_model.fit(X_train_final, y_train)
    
    preds = rf_model.predict(X_test_final)
    rmse = np.sqrt(mean_squared_error(y_test, preds))
    print("RMSE:", rmse)
    return rf_model

In [16]:
def xgboost_regressor(X_train_final, y_train, X_test_final, y_test, early_stopping_rounds=10, n_estimators=1000):
    from xgboost import XGBRegressor
    from sklearn.metrics import mean_squared_error
    
    xgb_model = XGBRegressor(
        device='cuda',
        early_stopping_rounds=early_stopping_rounds,  # to prevent overfitting
        eval_metric='rmse',       
        n_estimators=1000          
    )
    xgb_model.fit(
        X_train_final, y_train,
        eval_set=[(X_test_final, y_test)],
        verbose=True
    )
    preds = xgb_model.predict(X_test_final)
    rmse = np.sqrt(mean_squared_error(y_test, preds))
    print("RMSE:", rmse)
    return xgb_model

In [17]:
# Splitting the dataset into training and testing sets
from sklearn.model_selection import train_test_split
import numpy as np

X = df
y = df['likes']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# rmse = 4059.8200699045765

X_train_final, X_test_final, encoders = get_features(
    X_train, X_test,
    numerial_features=['char_count', 'sentiment_polarity', 'emoji_count', 'hashtag_count'],
    categorical_features=['media_type', 'inferred company', 'username']
)
xg_model = xgboost_regressor(X_train_final, y_train, X_test_final, y_test)
import joblib
joblib.dump(xg_model, 'model_1_xg.pkl')

features obtained
[0]	validation_0-rmse:4544.89843
[1]	validation_0-rmse:4412.84302
[2]	validation_0-rmse:4370.20807
[3]	validation_0-rmse:4254.94829
[4]	validation_0-rmse:4236.71899
[5]	validation_0-rmse:4221.16636
[6]	validation_0-rmse:4151.84740
[7]	validation_0-rmse:4148.59078
[8]	validation_0-rmse:4143.12054
[9]	validation_0-rmse:4118.64228
[10]	validation_0-rmse:4111.54815
[11]	validation_0-rmse:4107.10485
[12]	validation_0-rmse:4115.08432
[13]	validation_0-rmse:4110.98414
[14]	validation_0-rmse:4119.05668
[15]	validation_0-rmse:4122.84389
[16]	validation_0-rmse:4116.14755
[17]	validation_0-rmse:4106.60542
[18]	validation_0-rmse:4104.66015
[19]	validation_0-rmse:4103.48976
[20]	validation_0-rmse:4070.06343
[21]	validation_0-rmse:4068.46054
[22]	validation_0-rmse:4070.21454
[23]	validation_0-rmse:4059.82013
[24]	validation_0-rmse:4074.72556
[25]	validation_0-rmse:4070.19550
[26]	validation_0-rmse:4067.68653
[27]	validation_0-rmse:4064.96783
[28]	validation_0-rmse:4082.07645
[29]	validation_0-rmse:4079.21185
[30]	validation_0-rmse:4084.57514
[31]	validation_0-rmse:4084.21044
[32]	validation_0-rmse:4088.00570

c:\Users\swaya\OneDrive\Documents\GitHub\AI_and_Dev_Swayam_Pandey_CSoT\.venv\Lib\site-packages\xgboost\core.py:729: UserWarning: [00:27:16] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\common\error_msg.cc:58: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)

RMSE: 4059.8200699045765

['model_0_xg.pkl']

In [26]:
# RMSE: 4050.0509873333694

X_train_final, X_test_final, encoders = get_features(
    X_train, X_test,
    numerial_features=['char_count', 'sentiment_polarity', 'emoji_count', 'hashtag_count', 'followers', 'following'],
    categorical_features=['media_type'],
)
xg_model = xgboost_regressor(X_train_final, y_train, X_test_final, y_test)
import joblib
joblib.dump(xg_model, 'model_2_xg.pkl')
for i in encoders:
    joblib.dump(encoders[i], f'encoder_{i}_2_xg.pkl')

features obtained
[0]	validation_0-rmse:4684.85254
[1]	validation_0-rmse:4414.44616
[2]	validation_0-rmse:4246.47790
[3]	validation_0-rmse:4167.79314
[4]	validation_0-rmse:4112.14107
[5]	validation_0-rmse:4092.36410
[6]	validation_0-rmse:4085.37174
[7]	validation_0-rmse:4079.53034
[8]	validation_0-rmse:4064.19453
[9]	validation_0-rmse:4075.45899
[10]	validation_0-rmse:4072.56416
[11]	validation_0-rmse:4077.20844
[12]	validation_0-rmse:4072.43461
[13]	validation_0-rmse:4069.67871
[14]	validation_0-rmse:4067.98524
[15]	validation_0-rmse:4069.53656
[16]	validation_0-rmse:4065.25084
[17]	validation_0-rmse:4054.98847
[18]	validation_0-rmse:4052.49727
[19]	validation_0-rmse:4056.12529
[20]	validation_0-rmse:4058.66548
[21]	validation_0-rmse:4056.69763
[22]	validation_0-rmse:4055.82210
[23]	validation_0-rmse:4055.62721
[24]	validation_0-rmse:4050.05104
[25]	validation_0-rmse:4051.44191
[26]	validation_0-rmse:4054.27273
[27]	validation_0-rmse:4079.71581
[28]	validation_0-rmse:4081.22899
[29]	validation_0-rmse:4081.16936
[30]	validation_0-rmse:4079.73613
[31]	validation_0-rmse:4081.49278
[32]	validation_0-rmse:4083.15615
[33]	validation_0-rmse:4079.15032
[34]	validation_0-rmse:4083.28035
RMSE: 4050.0509873333694

with hour rmse turned out to be higher (~4330)<br>
with sentiment_subjectivity, rmse turned out to be higher (4276)

In [28]:
# RMSE: 4332.59771449873, will take 3-4 hours
X_train_final, X_test_final = get_features(
    X_train, X_test,
    numerial_features=['char_count', 'sentiment_polarity', 'emoji_count', 'hashtag_count', 'followers', 'following'],
    categorical_features=['media_type', 'inferred company', 'username'],
    avg_likes=['username', 'inferred company']
)
rf_model = random_forest_regressor(X_train_final, y_train, X_test_final, y_test)

KeyboardInterrupt:

In [29]:
bert_embedding = pd.read_csv('embeddings.csv')

In [ ]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')

embeddings = model.encode(df['content'].tolist(), show_progress_bar=True, convert_to_numpy=True)
print(embeddings.shape)
print(embeddings)

In [30]:
import torch
import torch.nn as nn

class Like_Predictor(nn.Module):
    def __init__(self, embedding_dimension, numerical_features_count, categorical_features_dict):
        super().__init__()
        # Dense layer for the CLS embedding
        self.bert_embeddings_layer = nn.Sequential(
            nn.Linear(embedding_dimension, 128),
            nn.ReLU()
        )
        # Embedding layers for categorical features
        self.categorical_embeddings_layer = nn.ModuleDict({
            name: nn.Embedding(num_classes, emb_dim)
            for name, (num_classes, emb_dim) in categorical_features_dict.items()
        })
        # Dense for structured numerical features
        self.numerical_features_layer = nn.Sequential(
            nn.Linear(numerical_features_count, 32),
            nn.ReLU()
        )
        # Final classifier
        total_dim = 128 + 32 + sum(emb_dim for _, (_, emb_dim) in categorical_features_dict.items())
        self.final_nn = nn.Sequential(
            nn.Linear(total_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 1)
        )

    def forward(self, bert_embedding, numerical_features, categorical_features):
    
        bert_embeds_layer = self.bert_embeddings_layer(bert_embedding)  # (batch, 128)
        num_layer = self.numerical_features_layer(numerical_features)  # (batch, 32)
        # Process categorical features
        cat_embeds = [
            self.categorical_embeddings_layer[name](categorical_features[name])  # (batch, emb_dim)
            for name in self.categorical_embeddings_layer
        ]
        # Concatenate categorical embeddings
        cat_embeds_layer = torch.cat(cat_embeds, dim=1) if cat_embeds else None

        if cat_embeds_layer is not None:
            all_features_layer = torch.cat([bert_embeds_layer, num_layer, cat_embeds_layer], dim=1)
        else:
            all_features_layer = torch.cat([bert_embeds_layer, num_layer], dim=1)
        out = self.final_nn(all_features_layer)
        return out.squeeze(1)  # (batch,)

In [32]:
numerical_features = pd.concat = df[['char_count', 'emoji_count', 'hashtag_count', 'followers', 'following', 'statusesCount', 'favouritesCount', 'mediaCount']]

In [33]:
# changing where 'verifiedType' is null to 'None'
df['verifiedType'] = df['verifiedType'].fillna('None')

In [34]:
categorical_features = {
    'media_type': df['media_type'].astype('category').cat.codes,
    'hour': df['hour'],
    'verifiedType': usernames_data['verifiedType'].astype('category').cat.codes
}

In [40]:
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Configuration
embedding_dimension = 384
numerical_features_count = 8 # char_count, followers, following, statusesCount, favouritesCount, mediaCount, emoji_count, hashtag_count
categorical_features_dict = {
    'media_type': (3, 8),     # 4 types, 8-dim embedding
    'hour': (24, 4),     # 24 hours, 4-dim embedding
    'verifiedType': (3, 4)  # 3 types, 4-dim embedding
}

# Model
model = Like_Predictor(embedding_dimension, numerical_features_count, categorical_features_dict).to(device)

# Dummy batch data

batch_size = 30

targets = df['likes']

optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
criterion = nn.MSELoss()
model.train()
# Training step
for i in range(0, len(bert_embedding), batch_size):
    bert_embedding_batch = torch.tensor(bert_embedding[i:i + batch_size].values, dtype=torch.float32).to(device)
    numerical_features_batch = torch.tensor(numerical_features[i:i + batch_size].values, dtype=torch.float32).to(device)
    categorical_features_batch = {
        name: torch.tensor(categorical_features[name][i:i + batch_size].values, dtype=torch.long).to(device)
        for name in categorical_features
    }
    targets_batch = torch.tensor(targets[i:i + batch_size].values, dtype=torch.float32).to(device)

    optimizer.zero_grad()
    outputs = model(bert_embedding_batch, numerical_features_batch, categorical_features_batch)
    loss = criterion(outputs, targets_batch)
    loss.backward()
    optimizer.step()
    print(f"Batch {i // batch_size + 1}, Loss: {loss.item()}")
# Save the model
joblib.dump(model, 'like_predictor_nn.pkl')

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.